import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
type Post= {
  id: number
  title: string
  content: string
  userId: number
  authorId: number
  published: boolean
}
type Props = {
  posts: Post[],
}
function Home({ posts }: Props) {
  return (
    <div>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{alignContent: 'center', padding: "30px"}}>
      <h2>
          ジョジョ名言
        </h2>


        {posts.map((post, index) => (
                <p key={index}><a href={`posts/${post.id}`}>{post.title}</a></p>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
export async function http<T>(
  request: RequestInfo
): Promise<T> {
  const response = await fetch(request);
  let body;
  try {
    body = await response.json();
  } catch (error) {
    body = {};
  }
  return body;
}
export async function getStaticProps() {

  const posts = await http<Post>(`http://nest:3000/feed`)
  return {
    props: {
      posts,
    },
  }
}